#!/usr/bin/perl

print "Compiling unwrapped_structure.cpp \n";

system("g++ -std=c++11 -o3 unwrapped_structure.cpp nodenetwork.cpp pixelnetwork.cpp -o unwrapped") == 0 or die;

print "\n To Run: ./unwrapped <ANG> <ANG2> <INTER> <MAXTRAJ> <XYZFILE> \n"; 
 
