#!/usr/bin/perl

print "Compiling main_structure.cpp \n";

system("g++ -std=c++11 -o3 main_structure.cpp nodenetwork.cpp pixelnetwork.cpp -o wrapped") == 0 or die;

print "\n To Run: ./wrapped <ANG> <ANG2> <INTER> <MAXTRAJ> <XYZFILE> \n"; 
 
